version: '3.8'

services:
  web:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: watchscout_php
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: watchscout_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: watchscout
      MYSQL_USER: watchscout
      MYSQL_PASSWORD: watchscout
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
